// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGpAj6zjsaZnY--L6WkmCKGkeNiMtVop0',
    appId: '1:721628597741:web:707142f1c46ea17fa1ebe4',
    messagingSenderId: '721628597741',
    projectId: 'solution-w',
    authDomain: 'solution-w.firebaseapp.com',
    storageBucket: 'solution-w.appspot.com',
    measurementId: 'G-9HW30R6HM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0hx3V0M8TK9ik00H-IXTipQTtBVs5Ync',
    appId: '1:721628597741:android:96e952d46342baeda1ebe4',
    messagingSenderId: '721628597741',
    projectId: 'solution-w',
    storageBucket: 'solution-w.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfu0phGi1G10q_LcLvLap62YS5Q6imLl4',
    appId: '1:721628597741:ios:acc13664554a5178a1ebe4',
    messagingSenderId: '721628597741',
    projectId: 'solution-w',
    storageBucket: 'solution-w.appspot.com',
    iosBundleId: 'com.example.solution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfu0phGi1G10q_LcLvLap62YS5Q6imLl4',
    appId: '1:721628597741:ios:f7fc48490df33430a1ebe4',
    messagingSenderId: '721628597741',
    projectId: 'solution-w',
    storageBucket: 'solution-w.appspot.com',
    iosBundleId: 'com.example.solution.RunnerTests',
  );
}
